sudo: required
language: generic
services: 
  - docker
before_install:
  - docker build -t madhub4u47/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true madhub4u47/docker-react npm run test -- --coverage